# Generated by Django 3.1.1 on 2020-09-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('formfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='other_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
